markdown: rdiscount
permalink: /:title/
url: http://lvlvforever.github.io/
highlighter: pygments
name: lvlvforever
description: lvlvforever | 吾尝终日而思矣，不如须臾之所学也；吾尝跂而望矣，不如登高之博见也。
author: lvlvforever
email: daipengdzzx#gmail.com
duoshuo: lvlvforever
weibo: lvlvbuaa
hub: lvlvforever
safe: true
paginate: 50
about: "hello world"
host: 0.0.0.0
